web stack debugging

diff --git a/0x0E-web_stack_debugging_1/0-nginx_likes_port_80 b/0x0E-web_stack_debugging_1/0-nginx_likes_port_80
--- a/0x0E-web_stack_debugging_1/0-nginx_likes_port_80
+++ b/0x0E-web_stack_debugging_1/0-nginx_likes_port_80
@@ -5,20 +5,24 @@ if ! command -v nginx &> /dev/null; then
 	echo "Nginx is not installed"
 	exit 1
 fi
-if ! pgrep nginx &> /dev/null then
-	echo "Nginx is starting..."
-	service nginx start
+if curl -s 0:80 &> /dev/null; then
+        echo "Nginx is already listening on port 80"
+        exit 0
 fi
-if ! lsof -i :80 &> /dev/null; then
-	echo "Nginx is not listening on port 80"
+if systemctl is-active --quiet nginx; then
+        echo "Nginx is already running but not listening to port 80"
 else
-	echo "Nginx is now listening on port 80"
-	exit 1
+        echo "Nginx is starting..."
+        service nginx start
 fi
-if ! ufw status | grep "80" &> /dev/null; then
-	echo "Firewall is not allowing traffic on port 80, enabling it..."
-	ufw allow 80
+echo "Configuring Nginx to listen on port 80..."
+sed -i 's/^listen\s*80;$/listen 80 default_server;/g' /etc/nginx/sites-available/default
+echo "Reloding Nginx..."
+service nginx reload
+if curl -s 0:80 &> /dev/null; then
+        echo "Nginx is now listening on port 80"
+else
+        echo "Failed to configure Nginx to listen on port 80"
+        exit 1
 fi
-echo "Restarting Nginx..."
-service nginx restart
-echo "Nginx is now configured to listen on port 80"
+exit 0
